### PR TITLE
Fix X7 sd logs

### LINKED ISSUE #4461: 2 stray columns in X7 logs
Between Ail and S1

### PR DESCRIPTION
**Pull request by 3djc**
This fixes #4461

### CODE REVIEW

File: radio/src/logs.cpp [hunk 1]
```diff
@@ -350,7 +350,11 @@ void logsWrite()
           GET_2POS_STATE(SE),
           GET_3POS_STATE(SF));
 #elif defined(PCBTARANIS) || defined(PCBHORUS)
+#if defined(PCBX7)
```
Comment (projectkk2glider) [inline radio/src/logs.cpp]: Perhaps X7 could have its own whole section (lilke flamenco) since it has 3 differences.

**Comment by projectkk2glider** [comment]
:+1:
