### PR TITLE
Fix haptic getCapabilities()

### LINKED ISSUE #7570: Companion V2.3.7  Profil X9D+ 2019  or Se 2019  no Haptik selection possible
V2.3.7, Profil X9D+ 2019  and at X9D+2019 SE  at  X9D+ is ok
No Haptik at spezialfunktion
No Haptik at Tx setting
Haptik

### PR DESCRIPTION
**Pull request by 3djc**
This fixes #7570

### CODE REVIEW

File: companion/src/firmwares/opentx/opentxinterface.cpp [hunk 1]
```diff
@@ -564,7 +564,7 @@ int OpenTxFirmware::getCapability(::Capability capability)
     case SoundPitch:
       return 1;
     case Haptic:
-      return (IS_2560(board) || IS_SKY9X(board) || IS_TARANIS_PLUS(board) || IS_TARANIS_SMALL(board) || IS_TARANIS_X9E(board) || IS_FAMILY_HORUS_OR_T16(board) || IS_JUMPER_T12(board) || id.contains("haptic"));
+      return !(board==Board::BOARD_TARANIS_X9D && !id.contains("haptic"));
```
Comment (bsongis) [inline companion/src/firmwares/opentx/opentxinterface.cpp]: avoid double negation!
board != Board::BOARD_TARANIS_X9D || id.contains("haptic")

File: companion/src/firmwares/boards.h [hunk 2]
```diff
@@ -286,6 +286,11 @@ inline bool IS_TARANIS_PLUS(Board::Type board)
   return board == Board::BOARD_TARANIS_X9DP || board == Board::BOARD_TARANIS_X9E;
 }
 
+inline bool IS_TARANIS_X9D_2019(Board::Type board)
```
Comment (bsongis) [inline companion/src/firmwares/boards.h]: needed?

Comment (3djc) [reply companion/src/firmwares/boards.h]: not used yet, but we can identify many radio, but not this one
