### PR TITLE
Fixes #2623: several fixes:

### LINKED ISSUE #2623: [Bug][OpenTX 2.0.17] No refesh after deleting a file
Hi folks,

From the SD CARD 2/8 menu when I'm deleting a file, it doesn't disappear from the list. I need to move to a parent folder then going back in the folder to see that it has been effectively removed.

### PR DESCRIPTION
**Pull request by projectkk2glider**
Disable menu for [..],
Refresh file list after delete,
Copy destination can be a directory,
Prevent copy/paste into the same directory,
Enabled renaming of directories and files without extension,
Removed delete menu option for directories,
Several simulator filesystem functions improved

Closes #2623 

Please test thoroughly before merging!

### CODE REVIEW

File: radio/src/gui/Taranis/menu_general_sdmanager.cpp [hunk 1]
```diff
@@ -36,7 +36,7 @@
 
 #include "../../opentx.h"
 
-#define REFRESH_FILES() reusableBuffer.sdmanager.offset = 65535
+#define REFRESH_FILES() reusableBuffer.sdmanager.offset = 65535; m_posVert = 0;
```
Comment (bsongis) [inline radio/src/gui/Taranis/menu_general_sdmanager.cpp]: This is dangerous, you should surround these 2 functions by a do { ... } while(0)

Comment (bsongis) [inline radio/src/gui/Taranis/menu_general_sdmanager.cpp]: Or perhaps only with (...)

File: radio/src/gui/Taranis/menu_general_sdmanager.cpp [hunk 2]
```diff
@@ -172,19 +172,31 @@ void onSdManagerMenu(const char *result)
   }
   else if (result == STR_PASTE) {
     f_getcwd(lfn, _MAX_LFN);
-    POPUP_WARNING(fileCopy(clipboard.data.sd.filename, clipboard.data.sd.directory, lfn));
-    REFRESH_FILES();
+    // if destination is dir, copy into that dir
+    if (!line[SD_SCREEN_FILE_LENGTH+1]) {
```
Comment (bsongis) [inline radio/src/gui/Taranis/menu_general_sdmanager.cpp]: Now I read this, I wonder why I didn't write a macro for this, it's difficult to read ...

File: radio/src/gui/Taranis/menu_general_sdmanager.cpp [hunk 3]
```diff
@@ -193,9 +205,6 @@ void onSdManagerMenu(const char *result)
     strcpy_P(statusLineMsg+min((uint8_t)strlen(statusLineMsg), (uint8_t)13), STR_REMOVED);
     showStatusLine();
     REFRESH_FILES();
-    if (m_posVert == reusableBuffer.sdmanager.count-1) {
-      m_posVert--;
-    }
```
Comment (bsongis) [inline radio/src/gui/Taranis/menu_general_sdmanager.cpp]: Ah yes, I inserted this code prior the commit where I added the REFRESH_FILES()

File: radio/src/gui/Taranis/menu_general_sdmanager.cpp [hunk 4]
```diff
@@ -296,6 +305,9 @@ void menuGeneralSdManager(uint8_t _event)
         killEvents(_event);
         char *line = reusableBuffer.sdmanager.lines[index];
         char *ext = getFileExtension(line, SD_SCREEN_FILE_LENGTH+1);
+        if (!strcasecmp(line, "..")) {
```
Comment (bsongis) [inline radio/src/gui/Taranis/menu_general_sdmanager.cpp]: strcmp will be fine here :)

File: radio/src/gui/Taranis/menu_general_sdmanager.cpp [hunk 5]
```diff
@@ -331,7 +343,8 @@ void menuGeneralSdManager(uint8_t _event)
           if (clipboard.type == CLIPBOARD_TYPE_SD_FILE)
             MENU_ADD_ITEM(STR_PASTE);
           MENU_ADD_ITEM(STR_RENAME_FILE);
-          MENU_ADD_ITEM(STR_DELETE_FILE);
+          if (line[SD_SCREEN_FILE_LENGTH+1])
```
Comment (bsongis) [inline radio/src/gui/Taranis/menu_general_sdmanager.cpp]: Macro again, aie!

File: radio/src/targets/simu/simpgmspace.cpp [hunk 6]
```diff
@@ -929,14 +929,24 @@ FRESULT f_mkdir (const TCHAR*)
   return FR_OK;
 }
 
-FRESULT f_unlink (const TCHAR*)
+FRESULT f_unlink (const TCHAR* name)
 {
+  char *path = convertSimuPath(name);
+  if (unlink(path)) {
```
Comment (bsongis) [inline radio/src/targets/simu/simpgmspace.cpp]: Ouch caution, I was used to simulate by removing real files, I will take care now ...

File: radio/src/targets/simu/simpgmspace.cpp [hunk 7]
```diff
@@ -929,14 +929,24 @@ FRESULT f_mkdir (const TCHAR*)
...
+    return FR_INVALID_NAME;
+  }
+  TRACE("f_unlink(%s) = OK", path);
   return FR_OK;
 }
 
 FRESULT f_rename(const TCHAR *oldname, const TCHAR *newname)
 {
-  TRACE("f_rename(%s, %s)", oldname, newname);
+  if ( rename(oldname, newname) < 0) {
```
Comment (bsongis) [inline radio/src/targets/simu/simpgmspace.cpp]: space before "rename" can be removed

File: radio/src/targets/simu/simpgmspace.cpp [hunk 8]
```diff
@@ -966,7 +976,12 @@ int f_printf (FIL *fil, const TCHAR * format, ...)
 
 FRESULT f_getcwd (TCHAR *path, UINT sz_path)
 {
-  strcpy(path, ".");
+  // remove simuSdDirectory from the cwd
+  char * cwd = get_current_dir_name();
+  std::string c(cwd + strlen(simuSdDirectory));
```
Comment (bsongis) [inline radio/src/targets/simu/simpgmspace.cpp]: Do we already use the stl in this file?

**Comment by bsongis** [comment]
I didn't test, only reviewed the code, but it's a good job, thanks!

**Comment by projectkk2glider** [comment]
@bsongis  Your comments addressed. Warning - not tested!

**Comment by bsongis** [comment]
Everything checked, thanks a lot, your mods make my code easier to read

**Comment by bsongis** [comment]
Tested, everything perfect, thanks!

**Comment by bsongis** [comment]
May I let you resolve the conflicts and push to 'master'?

**Comment by LapinFou** [comment]
Will it also be fixed in the 2.0.x branch?

**Comment by projectkk2glider** [comment]
>Will it also be fixed in the 2.0.x branch?

Yes.
