### PR TITLE
LUA horizontal and vertical lcd.drawLine(...) fix

### LINKED ISSUE #4608: lcd.drawLine(...) gives wrong result
There's still an issue with lcd.drawLine(...) on both the X7 and X9.

I didn't notice before I had a chance to try RC12, but in #4581 the stars are missing one pixel each on the bottom vertical line and the right horizontal line.

Other example of the same problem, these lines should be two pixels long, but are only one pixel long:
`lcd.drawLine(3, 1, 3, 2, SOLID, 0)`
`lcd.drawLine(1, 3, 2, 3, SOLID, 0)`

### PR DESCRIPTION
**Pull request by floaledm**
Fixes #4608 

Compiled and tested the #4581 script on an X9D+

### CODE REVIEW

File: radio/src/lua/api_lcd.cpp [hunk 1]
```diff
@@ -119,11 +119,11 @@ static int luaLcdDrawLine(lua_State *L)
 
   if (pat == SOLID) {
     if (x1 == x2) {
-      lcdDrawSolidVerticalLine(x1, y1<y2 ? y1 : y2,  y1<y2 ? y2-y1 : y1 - y2, flags);
+      lcdDrawSolidVerticalLine(x1, y1<y2 ? y1 : y2,  y1<y2 ? y2-y1+1 : y1-y2+1, flags);
```
Comment (3djc) [inline radio/src/lua/api_lcd.cpp]: Maybe explicitly set priority in all 4 instances, like  (y1-y2)+1

Comment (floaledm) [inline radio/src/lua/api_lcd.cpp]: Thanks for reviewing this. Just made your suggested change.

**Comment by 3djc** [comment]
Thanks a lot!
