### PR TITLE
x7/x9 GPS datetime fix

### LINKED ISSUE #5026: Open TX 2.2 Display GPS Date
Changed my Taranis  X9D from OpenTx 2.1.9 to  2.2.
Using Frskys GPS-II Sensor I have used GPS Date and Time as Telemetrie-Value.
In 2.2 Looks like there is a mismatch between Data and Display (justify left/right and some Overlay ?)
screenshot_x9d_17-06-11_20-31-24

In 2.1.9 looks Ok
screenshot-1

Ralf

### PR DESCRIPTION
**Pull request by 3djc**
This fixes #5026

image

image

### CODE REVIEW

File: radio/src/gui/212x64/lcd.cpp [hunk 1]
```diff
@@ -756,35 +756,20 @@ void drawGPSCoord(coord_t x, coord_t y, int32_t value, const char * direction, L
...
-    lcdDrawNumber(lcdNextPos, y, telemetryItem.datetime.year-2000, att|LEFT);
-    lcdDrawNumber(lcdNextPos+FW+1, y, telemetryItem.datetime.hour, att|LEADING0|LEFT, 2);
-    lcdDrawChar(lcdLastRightPos, y, ':', att);
-    lcdDrawNumber(lcdNextPos, y, telemetryItem.datetime.min, att|LEADING0|LEFT, 2);
-    lcdDrawChar(lcdLastRightPos, y, ':', att);
-    lcdDrawNumber(lcdNextPos, y, telemetryItem.datetime.sec, att|LEADING0|LEFT, 2);
-  }
+void drawTelemScreenDate(coord_t x, coord_t y, TelemetryItem & telemetryItem, LcdFlags att)
+{
+  att &= ~0x0F00; // TODO constant, remove DBLSIZE
```
Comment (bsongis) [inline radio/src/gui/212x64/lcd.cpp]: I know it is mine, but this is very horrible

Comment (bsongis) [reply radio/src/gui/212x64/lcd.cpp]: perhaps FONTSIZE_MASK?

File: radio/src/gui/128x64/lcd.h [hunk 2]
```diff
@@ -95,6 +95,7 @@
 
 #if defined(CPUARM)
   #define FONTSIZE(x)                  ((x) & 0x0700)
+  #define FONTSIZE_MASK(x)             ((x) & ~0x0F00)
```
Comment (bsongis) [inline radio/src/gui/128x64/lcd.h]:
```
#define FONTSIZE_MASK 0x0700
#define FONTSIZE(x) ((x) & FONTSIZE_MASK)
````

File: radio/src/gui/212x64/lcd.cpp [hunk 3]
```diff
@@ -756,42 +756,27 @@ void drawGPSCoord(coord_t x, coord_t y, int32_t value, const char * direction, L
...
-    lcdDrawNumber(lcdNextPos, y, telemetryItem.datetime.month, att|LEFT, 2);
-    lcdDrawChar(lcdLastRightPos-1, y, '-', att);
-    lcdDrawNumber(lcdNextPos, y, telemetryItem.datetime.year-2000, att|LEFT);
-    lcdDrawNumber(lcdNextPos+FW+1, y, telemetryItem.datetime.hour, att|LEADING0|LEFT, 2);
-    lcdDrawChar(lcdLastRightPos, y, ':', att);
-    lcdDrawNumber(lcdNextPos, y, telemetryItem.datetime.min, att|LEADING0|LEFT, 2);
-    lcdDrawChar(lcdLastRightPos, y, ':', att);
-    lcdDrawNumber(lcdNextPos, y, telemetryItem.datetime.sec, att|LEADING0|LEFT, 2);
-  }
+  att = FONTSIZE_MASK(att);
```
Comment (bsongis) [inline radio/src/gui/212x64/lcd.cpp]: `att &= ~FONTSIZE_MASK;`

I don't think it's useful to remove the VERTICAL 0x0800 flag

**Comment by bsongis** [comment]
Cool, thanks!
