### PR TITLE
[Companion] Fix RF Output Power setting getting reset to default on every update

### LINKED ISSUE #5954: [Companion] Changing failsafe mode reset the RF power field
Hi folks,

- Companion 2.2.2N627 Win version.
- Select FrSky **R9M Module** for external RF.
- Select a RF power different of the default one.

Each time the failsafe mode is change, this will reset the RF power field to its default value.

### PR DESCRIPTION
**Pull request by mpaperno**
RF Output Power would go back to default (first choice in combobox) every time the `update()` routine got run, which was quite often, including when [re-]opening the model editor.  

Also prevents some redundant updates.

Fixes #5954

### CODE REVIEW

File: companion/src/modeledit/setup.cpp [hunk 1]
```diff
@@ -483,6 +483,7 @@ void ModulePanel::update()
   ui->warning_r9mPower->setVisible((mask & MASK_R9M) && module.subType == R9M_LBT);
 
   if (mask & MASK_R9M) {
+    const QSignalBlocker blocker(ui->r9mPower);
```
Comment (mpaperno) [inline companion/src/modeledit/setup.cpp:486]: This is the main fix for RF power getting reset.

**Comment by 3djc** [comment]
Tested ok on xlite and standard size r9m ! 👍
