### PR TITLE
[Companion] Adjust source value ranges and editors in LS/CF/Telemetry

### LINKED ISSUE #2984: Negative timer value not possible in Logical Switches
I use a logical switch in order to trigger special function to start playing the timer value every 10 seconds when the value is smaller then -00:09. This will result in starting to play the announcements when it is -10 seconds and from then on repeats that every 10 seconds. I use Timer 2 for this and configured the timer to start counting down from 10 minutes. During the count down from 10 minutes I use the normal Minute call functionality to play the timer value every minute.

In order to achieve the additional (negative) announcements  I have done the following in the openTX firmware for my Taranis:

Logical Switches
L1    a<x    Tmr2    -00:09

Special Functions
SF1    L1    PlayValue    Tmr2    10s

So as soon as the timer value goes below 9 seconds L1 is true and the next announcement is played at -10 seconds and then continuing every 10 seconds (-10 seconds, -20 seconds, -30 seconds, etc.). This works very well and I am very happy with this.

The only annoying thing is that Companion does not support entering a negative value for the timer value in Companion. It reads the eepe file just right and even the simulator works fine with the eepe file retrieved from my Taranis. But the value in the Logical Switch shows as 00:00:00 [h:m:s]. If I would like to set this up with Companion itself it will not work as it does not allow to change the value to a negative value.

This has been in there for multiple 2.0 versions up to 2.0.17 and also still is the case for version 2.1.13. For all the corresponding firmware versions for the Taranis itself it works fine.

Would like to see this bug fixed in Companion as well.

### LINKED ISSUE #3581: Logical Switches: a>x etc.: x limited to le. 150 if a is the output of a lua script
For me, this is an interesting behaviour. I tried to set up a logical switch, which is triggered, if the calculated distance from a LUA-Script output is larger then 250(m). But 150 is the biggest number I can fill in for x. With other parameters for a (for ex. SWR and others) higher values for x are possible.
Would it be possible to increase the x-values for lua-scripts to higher values as well?

Best Regards Paul

### LINKED ISSUE #5362: Timer value limited to 1275 on Companion telemetry screen configure tab
Companion/Firmware 2.2.1N434 / Taranis X7 

Timer value limited to 1275 (1 unit = 20 ms so it is 4:15) whereas on the radio we can set it to 10:00 or 20:00

image

### LINKED ISSUE #5374: Logical Switch value list not refreshed after Telemetry added
Companion 2.2.1N436 / Taranis X7

- Create a new model
- Configure a telemetry sensor
- Go to Logical Switch tab
- Telemetry sensor not available until you close an re open the editing window

image

image

### LINKED ISSUE #5375: Decimal entry is difficult in V2 / Logical Switches
Companion 2.2.1N436 / Taranis X7

Language of the test computer is French (decimal separator is ",")

- Add a Volt telemetry sensor, name it A1, with precision 1
- Go to logical Switches and add a line
- Select "a<x", then "TELE1:A1"
- Select v2 content so you can replace it
- Type 12,1 with the keyboard you should get "12,0 V"

There is no issue with other decimal fields, it may be linked to the presence of the unit ? (The unit is refreshed after each keypress)

(This is a cosmetic issue, you can then select the value after the coma and replace it)

image

### LINKED ISSUE #5527: V2.2.1  Companion progamming log Switch Errors, shows not all log Switches defined
programming at Companion a new modell for X9E
look at example L1, L2, L3, 
then will make a L4
look at L4 AND   only the L01 is there, 
after close and open modell again then there are all on

At TX its ok

fehler log schalter rc3

### PR DESCRIPTION
**Pull request by mpaperno**
Went down a rabbit hole with regards to timer and RTC ranges and how they're used/limited/edited in regards to LS (comparison functions), CF (set timerN action), and telemetry display bar limits.  Seems there's a bit of confusion here both in Companion and on radio (probably due to legacy issues).

Fixes #2984
Fixes #5362  (also negative values were not possible)
Fixes #5374
Fixes #5375
Fixes #5527
Fixes timer and RTC time ranges to comply with firmware limits.
Fixes not being able to use RTC time in LSs.
Fixes newly-added LS not being available in source lists (except when pasting).
Fixes bug with timer/rtc comparison values getting reset to value of spin box instead of time editor.
New TimerEdit GUI component for negative and other typically "invalid" times.
Removed the short limits on timer values.
GVars, trims, script outputs, and sticks/switches/cyclic/MAX get proper limits.
Fixes #3581 (Companion part).
Fixes sensor value offset and range editing (mentioned in 3581).

There are some issues/questions on the firmware side... I found a couple small bugs and will open a separate PR and bring them up there.  

But the main question is why the limit of +/- 23m59s on timer values for LS comparison functions and telem. bar display min/max since the variable types (in firmware) can handle a lot more than that.

### CODE REVIEW

File: companion/src/modeledit/telemetry.cpp [hunk 1]
```diff
@@ -324,6 +325,13 @@ TelemetryCustomScreen::TelemetryCustomScreen(QWidget *parent, ModelData & model,
...
+    minTime[l] = new TimerEdit(this);
+    minTime[l]->setProperty("index", l);
+    minTime[l]->setProperty("type", "min");
+    connect(minTime[l], SIGNAL(editingFinished()), this, SLOT(barTimeChanged()));
+    ui->screenBarsLayout->addWidget(minTime[l], l, 1, 1, 1);
+    minTime[l]->hide();
+
     QLabel * label = new QLabel(this);
     label->setAutoFillBackground(false);
     label->setStyleSheet(QString::fromUtf8("Background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 128, 255), stop:0.339795 rgba(0, 0, 128, 255), stop:0.339799 rgba(255, 255, 255, 255), stop:0.662444 rgba(255, 255, 255, 255),)\n"""));
```
Comment (opentx-sonar) [inline companion/src/modeledit/telemetry.cpp]: MINOR Merge this literal with previous. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS3728)

File: companion/src/modeledit/telemetry.h [hunk 2]
```diff
@@ -82,6 +83,7 @@ class TelemetryCustomScreen: public ModelPanel
     void barSourceChanged(int index);
```
Comment (opentx-sonar) [inline companion/src/modeledit/telemetry.h]: MAJOR Remove this unused private function. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1144)

File: companion/src/modeledit/telemetry.h [hunk 3]
```diff
@@ -82,6 +83,7 @@ class TelemetryCustomScreen: public ModelPanel
...
     void barMinChanged(double value);
```
Comment (opentx-sonar) [inline companion/src/modeledit/telemetry.h]: MAJOR Remove this unused private function. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1144)

File: companion/src/modeledit/telemetry.h [hunk 4]
```diff
@@ -82,6 +83,7 @@ class TelemetryCustomScreen: public ModelPanel
...
     void barMaxChanged(double value);
```
Comment (opentx-sonar) [inline companion/src/modeledit/telemetry.h]: MAJOR Remove this unused private function. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1144)

File: companion/src/modeledit/telemetry.h [hunk 5]
```diff
@@ -82,6 +83,7 @@ class TelemetryCustomScreen: public ModelPanel
...
+    void barTimeChanged();
```
Comment (opentx-sonar) [inline companion/src/modeledit/telemetry.h]: MAJOR Remove this unused private function. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1144)

File: companion/src/modeledit/telemetry.h [hunk 6]
```diff
@@ -25,6 +25,7 @@
 #include "eeprominterface.h"
 
 class AutoComboBox;
+class TimerEdit;
 
 namespace Ui {
```
Comment (opentx-sonar) [inline companion/src/modeledit/telemetry.h]: MINOR Rename this namespace to match the regular expression: [a-z][a-z_0-9]*+ [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3ANamespaceName)

File: companion/src/shared/timeredit.cpp [hunk 7]
```diff
@@ -0,0 +1,281 @@
...
+  }
+  if (m_minTime < 0) {
+    inputRe.prepend("(?<pol>-|\\+|\\s)?");
+    inputMsk.prepend("#");
+  }
+
+  inputRe.prepend("^");
+  inputRe.append("\\s?\\[[^\\]]+\\]$");
+  inputMsk.append(" \\[" % suffx % "\\]");
+  //qDebug() << inputMsk << inputRe;
```
Comment (opentx-sonar) [inline companion/src/shared/timeredit.cpp]: MAJOR Remove this block of commented out code. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3ACommentedCode)

File: companion/src/shared/timeredit.cpp [hunk 8]
```diff
@@ -0,0 +1,281 @@
...
+int TimerEdit::timeInSeconds() const
+{
+  int ret = 0;
+
+  ret += timepart(text(), TimeParts::Hours) * 3600;
+  ret += timepart(text(), TimeParts::Minutes) * 60;
+  ret += timepart(text(), TimeParts::Seconds);
+  ret *= timepart(text(), TimeParts::Polarity);
+
+  //qDebug() << ret;
```
Comment (opentx-sonar) [inline companion/src/shared/timeredit.cpp]: MAJOR Remove this block of commented out code. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3ACommentedCode)

File: companion/src/shared/timeredit.cpp [hunk 9]
```diff
@@ -0,0 +1,281 @@
...
+  if (sec < m_minTime)
+    setTime(m_minTime);
+  else if (sec > m_maxTime)
+    setTime(m_maxTime);
+  else
+    return;
+
+  emitValueChanged();
+
+  //qDebug() << text() << sec << getTimeSeconds() << validator()->validate(text(), sec);
```
Comment (opentx-sonar) [inline companion/src/shared/timeredit.cpp]: MAJOR Remove this block of commented out code. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3ACommentedCode)

File: companion/src/shared/timeredit.cpp [hunk 10]
```diff
@@ -0,0 +1,281 @@
...
+    emitValueChanged();
+  }
+}
+
+void TimerEdit::setTimeRange(int minSeconds, int maxSeconds)
+{
+  if (minSeconds <= maxSeconds && (m_minTime != minSeconds || m_maxTime != maxSeconds)) {
+    int digits = 0;
+    if (maxSeconds >= 3600)
+      digits = floorf(logf(round(maxSeconds / 3600)) / logf(10.0f)) + 1;
```
Comment (opentx-sonar) [inline companion/src/shared/timeredit.cpp]: MINOR Uppercase the literal suffix. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3ALiteralSuffix)

File: companion/src/shared/timeredit.cpp [hunk 11]
```diff
@@ -0,0 +1,281 @@
...
+          ret = -1;
+        else
+          ret = 1;
+        break;
+
+      default:
+        break;
+    }
+  }
+  //qDebug() << input << match << ret;
```
Comment (opentx-sonar) [inline companion/src/shared/timeredit.cpp]: MAJOR Remove this block of commented out code. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3ACommentedCode)

File: companion/src/shared/timeredit.cpp [hunk 12]
```diff
@@ -0,0 +1,281 @@
...
+  if (m_showSeconds)
+    val.append(QString(":%1").arg(qrM.rem, 2, 10, QChar('0')));
+
+  if (m_minTime < 0) {
+    if (seconds < 0)
+      val.prepend("-");
+    else
+      val.prepend(" ");
+  }
+  //qDebug() << seconds << qrH.quot << qrH.rem << qrM.quot << qrM.rem << val << text();
```
Comment (opentx-sonar) [inline companion/src/shared/timeredit.cpp]: MAJOR Remove this block of commented out code. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3ACommentedCode)

File: companion/src/modeledit/logicalswitches.h [hunk 13]
```diff
@@ -37,12 +38,16 @@ class LogicalSwitchesPanel : public ModelPanel
...
   private slots:
-    void edited();
+    void setDataModels();
+    void functionChanged();
     void v1Edited(int value);
     void v2Edited(int value);
     void andEdited(int value);
     void durationEdited(double duration);
     void delayEdited(double delay);
+    void offsetEdited();
```
Comment (opentx-sonar) [inline companion/src/modeledit/logicalswitches.h]: MAJOR Remove this unused private function. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1144)

File: companion/src/modeledit/logicalswitches.h [hunk 14]
```diff
@@ -37,12 +38,16 @@ class LogicalSwitchesPanel : public ModelPanel
...
+    bool offsetEditedAt(int index);
+    void updateLine(int index);
     void csw_customContextMenuRequested(QPoint pos);
```
Comment (opentx-sonar) [inline companion/src/modeledit/logicalswitches.h]: MAJOR Remove this unused private function. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1144)

File: companion/src/modeledit/logicalswitches.h [hunk 15]
```diff
@@ -37,12 +38,16 @@ class LogicalSwitchesPanel : public ModelPanel
     virtual void update();
```
Comment (opentx-sonar) [inline companion/src/modeledit/logicalswitches.h]: CRITICAL Rename this member function so that it doesn't hide an inherited non-virtual function, or make it virtual in the base class "QWidget". [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1242)

File: companion/src/modeledit/logicalswitches.h [hunk 16]
```diff
@@ -37,12 +38,16 @@ class LogicalSwitchesPanel : public ModelPanel
...
 
   private slots:
-    void edited();
+    void setDataModels();
+    void functionChanged();
```
Comment (opentx-sonar) [inline companion/src/modeledit/logicalswitches.h]: MAJOR Remove this unused private function. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1144)

File: companion/src/modeledit/logicalswitches.h [hunk 17]
```diff
@@ -37,12 +38,16 @@ class LogicalSwitchesPanel : public ModelPanel
...
     void v1Edited(int value);
```
Comment (opentx-sonar) [inline companion/src/modeledit/logicalswitches.h]: MAJOR Remove this unused private function. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1144)

File: companion/src/modeledit/logicalswitches.h [hunk 18]
```diff
@@ -37,12 +38,16 @@ class LogicalSwitchesPanel : public ModelPanel
...
     void v2Edited(int value);
```
Comment (opentx-sonar) [inline companion/src/modeledit/logicalswitches.h]: MAJOR Remove this unused private function. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1144)

File: companion/src/modeledit/logicalswitches.h [hunk 19]
```diff
@@ -37,12 +38,16 @@ class LogicalSwitchesPanel : public ModelPanel
...
     void andEdited(int value);
```
Comment (opentx-sonar) [inline companion/src/modeledit/logicalswitches.h]: MAJOR Remove this unused private function. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1144)

File: companion/src/modeledit/logicalswitches.h [hunk 20]
```diff
@@ -37,12 +38,16 @@ class LogicalSwitchesPanel : public ModelPanel
...
     void durationEdited(double duration);
```
Comment (opentx-sonar) [inline companion/src/modeledit/logicalswitches.h]: MAJOR Remove this unused private function. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1144)

File: companion/src/modeledit/logicalswitches.h [hunk 21]
```diff
@@ -37,12 +38,16 @@ class LogicalSwitchesPanel : public ModelPanel
...
     void delayEdited(double delay);
```
Comment (opentx-sonar) [inline companion/src/modeledit/logicalswitches.h]: MAJOR Remove this unused private function. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1144)

File: companion/src/modeledit/logicalswitches.cpp [hunk 22]
```diff
@@ -303,52 +333,56 @@ void LogicalSwitchesPanel::updateTimerParam(QDoubleSpinBox *sb, int timer, doubl
...
+  cswitchAnd[i]->setCurrentIndex(cswitchAnd[i]->findData(RawSwitch(model->logicalSw[i].andsw).toValue()));
+
   if (!model->logicalSw[i].func) {
     mask = 0;
   }
   else {
-    mask = DELAY_ENABLED | DURATION_ENABLED;
+    mask = LINE_ENABLED | DELAY_ENABLED | DURATION_ENABLED;
+
     switch (model->logicalSw[i].getFunctionFamily())
```
Comment (opentx-sonar) [inline companion/src/modeledit/logicalswitches.cpp]: CRITICAL Add a "default" case to this switch statement. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3ASwitchWithoutDefault)

File: companion/src/modeledit/logicalswitches.cpp [hunk 23]
```diff
@@ -303,52 +333,56 @@ void LogicalSwitchesPanel::updateTimerParam(QDoubleSpinBox *sb, int timer, doubl
...
     {
       case LS_FAMILY_VOFS:
       {
```
Comment (opentx-sonar) [inline companion/src/modeledit/logicalswitches.cpp]: MINOR Extract this nested code block into a separate method. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1199)

File: companion/src/modeledit/logicalswitches.cpp [hunk 24]
```diff
@@ -303,52 +333,56 @@ void LogicalSwitchesPanel::updateTimerParam(QDoubleSpinBox *sb, int timer, doubl
...
         mask |= SOURCE1_VISIBLE;
         RawSource source = RawSource(model->logicalSw[i].val1);
         RawSourceRange range = source.getRange(model, generalSettings, model->logicalSw[i].getRangeFlags());
+        double value = range.step * model->logicalSw[i].val2 + range.offset;  /* TODO+source.getRawOffset(model)*/
```
Comment (opentx-sonar) [inline companion/src/modeledit/logicalswitches.cpp]: INFO Complete the task associated to this "TODO" comment. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1135)

File: companion/src/modeledit/logicalswitches.cpp [hunk 25]
```diff
@@ -510,7 +522,6 @@ void LogicalSwitchesPanel::cswPaste()
     LogicalSwitchData *csw = &model->logicalSw[selectedSwitch];
```
Comment (opentx-sonar) [inline companion/src/modeledit/logicalswitches.cpp]: MAJOR Rename "csw" which hides a class field with same name. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1117)

File: companion/src/modeledit/logicalswitches.cpp [hunk 26]
```diff
@@ -208,75 +248,65 @@ void LogicalSwitchesPanel::delayEdited(double delay)
...
 
-    switch (newFuncFamily)
+  lock = true;
+  bool mod = false;
+  int value;
+
+  switch (model->logicalSw[index].getFunctionFamily())
+  {
+    case LS_FAMILY_VOFS:
     {
```
Comment (opentx-sonar) [inline companion/src/modeledit/logicalswitches.cpp]: MINOR Extract this nested code block into a separate method. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1199)

File: companion/src/shared/timeredit.h [hunk 27]
```diff
@@ -0,0 +1,82 @@
...
+    int timeInSeconds() const;
+    int timepart(const QString & input, TimeParts part) const;
+
+    bool showSeconds() const { return m_showSeconds; }
+    int minimumTime() const { return m_minTime; }
+    int maximumTime() const { return m_maxTime; }
+    unsigned int singleStep() const { return m_singleStep; }
+    unsigned int pageStep() const { return m_pageStep; }
+
+  public slots:
```
Comment (opentx-sonar) [inline companion/src/shared/timeredit.h]: MINOR Remove this redundant access specifier; it does not change the accessibility level. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS3539)

File: companion/src/shared/timeredit.h [hunk 28]
```diff
@@ -0,0 +1,82 @@
...
+    void setPageStep(unsigned int pageStep) { m_pageStep = pageStep; }
+
+  protected:
+    void textEditedHandler();
+    void setupFormat();
+    void emitValueChanged();
+    void keyPressEvent(QKeyEvent * event) Q_DECL_OVERRIDE;
+    void wheelEvent(QWheelEvent * event) Q_DECL_OVERRIDE;
+
+    bool m_showSeconds;
```
Comment (opentx-sonar) [inline companion/src/shared/timeredit.h]: CRITICAL Make this member variable "private". [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS3656)

File: companion/src/shared/timeredit.h [hunk 29]
```diff
@@ -0,0 +1,82 @@
...
+    int m_minTime;  // seconds
```
Comment (opentx-sonar) [inline companion/src/shared/timeredit.h]: CRITICAL Make this member variable "private". [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS3656)

File: companion/src/shared/timeredit.h [hunk 30]
```diff
@@ -0,0 +1,82 @@
...
+    int m_maxTime;  // seconds
```
Comment (opentx-sonar) [inline companion/src/shared/timeredit.h]: CRITICAL Make this member variable "private". [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS3656)

File: companion/src/shared/timeredit.h [hunk 31]
```diff
@@ -0,0 +1,82 @@
...
+    Q_PROPERTY(int maximumTime READ maximumTime WRITE setMaximumTime)
+    Q_PROPERTY(bool showSeconds READ showSeconds WRITE setShowSeconds)
+    Q_PROPERTY(unsigned int singleStep READ singleStep WRITE setSingleStep)
+    Q_PROPERTY(unsigned int pageStep READ pageStep WRITE setPageStep)
+
+
+  public:
+    enum TimeParts {Whole, Polarity, Hours, Minutes, Seconds};
+
+    TimerEdit(QWidget * parent = Q_NULLPTR);
```
Comment (opentx-sonar) [inline companion/src/shared/timeredit.h]: CRITICAL Add the "explicit" keyword to this constructor. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1709)

File: companion/src/shared/timeredit.h [hunk 32]
```diff
@@ -0,0 +1,82 @@
...
+    void textEditedHandler();
+    void setupFormat();
+    void emitValueChanged();
+    void keyPressEvent(QKeyEvent * event) Q_DECL_OVERRIDE;
+    void wheelEvent(QWheelEvent * event) Q_DECL_OVERRIDE;
+
+    bool m_showSeconds;
+    int m_minTime;  // seconds
+    int m_maxTime;  // seconds
+    unsigned m_singleStep;  // seconds
```
Comment (opentx-sonar) [inline companion/src/shared/timeredit.h]: CRITICAL Make this member variable "private". [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS3656)

File: companion/src/shared/timeredit.h [hunk 33]
```diff
@@ -0,0 +1,82 @@
...
+    unsigned m_pageStep;    // seconds
```
Comment (opentx-sonar) [inline companion/src/shared/timeredit.h]: CRITICAL Make this member variable "private". [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS3656)

File: companion/src/shared/timeredit.h [hunk 34]
```diff
@@ -0,0 +1,82 @@
...
+    short m_hourDigits;
```
Comment (opentx-sonar) [inline companion/src/shared/timeredit.h]: CRITICAL Make this member variable "private". [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS3656)

File: companion/src/shared/timeredit.h [hunk 35]
```diff
@@ -0,0 +1,82 @@
...
+    QRegularExpressionValidator * m_validator;
```
Comment (opentx-sonar) [inline companion/src/shared/timeredit.h]: CRITICAL Make this member variable "private". [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS3656)

File: companion/src/eeprominterface.cpp [hunk 36]
```diff
@@ -260,9 +255,7 @@ RawSourceRange RawSource::getRange(const ModelData * model, const GeneralSetting
         result.unit = sensor.unitString();
       }
       else {
-        if (singleprec) {
-          result.offset = -DBL_MAX;
-        }
+        result.offset = -DBL_MAX;
 
         switch (index) {
```
Comment (opentx-sonar) [inline companion/src/eeprominterface.cpp]: MAJOR Reduce the number of switch cases from 50 to at most 30. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1479)

**Comment by kilrah** [comment]
Nice!!

>But the main question is why the limit of +/- 23m59s on timer values for LS comparison functions and telem. bar display min/max since the variable types (in firmware) can handle a lot more than that.

I think it was a limit somewhere on 9X Stock AVR at least at some point...

**Comment by mpaperno** [comment]
This PR relates to #5445 and should be merged together.  I wasn't really sure if it was clearer to separate them or put them both together. 

Removed the short limits on timer values.
GVars, trims, script outputs, and sticks/switches/cyclic/MAX get proper limits.
Fixes #3581 (Companion part).
Fixes sensor value offset and range editing (mentioned in 3581).

**Comment by elecpower** [comment]
@mpaperno should the TimerEdit class also be applied to the timers in Model Setup?

**Comment by mpaperno** [comment]
Hi Neil, not really necessary to use it there since the timer start setting doesn't accept negative numbers.  Though it could be good for UI consistency I suppose.

**Comment by mpaperno** [comment]
Rebased.
