### PR TITLE
[companion][log viewer]fix performance decrease if selection (fixes #2199)

### LINKED ISSUE #2199: log viewer plotting time changes when there is some selection
If some data is selected, like a fly session, the plotting time is noticeable longer than when no data is selected and all data is used.

Didn't find the specific details but it's related to Qt "isSelected" implementation...

I will put a pull request soon with some changes to not use "isSelected". This way there is no change in performance anymore. (this code is already on next, on my last pull request #2191)

### PR DESCRIPTION
**Pull request by griebd**
Performance is now the same, with or without selection.
Removed some unused stuff too.

### CODE REVIEW

File: companion/src/logsdialog.cpp [hunk 1]
```diff
@@ -128,12 +120,11 @@ void logsDialog::legendDoubleClick(QCPLegend *legend, QCPAbstractLegendItem *ite
 {
   // Rename a graph by double clicking on its legend item
 
-  Q_UNUSED(legend)
   if (item) // only react if item was clicked (user could have clicked on border padding of legend where there is no item, then item is 0)
   {
     QCPPlottableLegendItem *plItem = qobject_cast<QCPPlottableLegendItem*>(item);
     bool ok;
-    QString newName = QInputDialog::getText(this, "QCustomPlot example", "New graph name:", QLineEdit::Normal, plItem->plottable()->name(), &ok);
+    QString newName = QInputDialog::getText(this, "Graph Name Change", "New graph name:", QLineEdit::Normal, plItem->plottable()->name(), &ok);
```
Comment (bsongis) [inline companion/src/logsdialog.cpp]: Missing tr(...)

**Comment by griebd** [comment]
Quite true, probably in next too... Will add here and make a new pull request for next, ok?

**Comment by bsongis** [comment]
Perfect, thanks!
