### PR TITLE
Fixes #1997: firmware upload failed when "Check Firmware Compatibility" ...

### LINKED ISSUE #1997: Problems loading firmware with Companin 2.0.14
Same problems exist with downloaded Companion 2.0.14 on Windows 7 and self compiled Companion from tag 2.0.14 on openSuSe 13.2. to a Rev. B Taranis
  
1.  Firmware load with Taranis mounted as removable device completes, but Taranis hangs and won't power off.  Have to pull battery to power off.  Turning on and hangs at splash screen and won't power off.  Tried loading opentx-taranis-lua-nooverridech-en-2.0.14.bin and opentx-taranis-lua-nooverridech-en-2.0.13.bin and both hang and won't power off.

2.  Copy opentx-taranis-lua-nooverridech-en-2.0.14 as opentx-2_0_14 to FIRMWARES on SD and update completes and Taranis boots but has default splash screen instead of custom.

3.  Flash firmware from 2.0.14 Companion using DFU and Taranis works, but again have default splash screen instead of custom.

4.  Flashed opentx-taranis-lua-nooverridech-en-2.0.14.bin firmware using Companin 2.0.13 with Taranis mounted as removable device and flash completed, Taranis worked, and I had my custom splash.

Jim

### PR DESCRIPTION
**Pull request by projectkk2glider**
...was selected

Closes #1997 

I've tested this on Linux with *fake* Taranis - just an USB key with FIRMWARE.BIN file. But it works - the contents of FIRMWARE.BIN get changed to desired state.

We need somebody to test this on Windows and with real radio.

The diff is not very nice, because I also changed indentation.

### CODE REVIEW

File: companion/src/mainwindow.cpp [hunk 1]
```diff
@@ -1294,92 +1298,109 @@ bool MainWindow::convertEEPROM(QString backupFile, QString restoreFile, QString
...
+  cd->exec();
+  qDebug() << "MainWindow::writeFlash(): flashing " << fileName;
+  
+  if (IS_TARANIS(GetEepromInterface()->getBoard())) {
+    backup=false;
+  }
+
+  if (!fileName.isEmpty()) {
+    if (g.checkHardwareCompatibility()) {
+      QString tempFlash = generateProcessUniqueTempFileName("flash-check.bin");
```
Comment (projectkk2glider) [inline companion/src/mainwindow.cpp]: This is the most important change, the file name for check is now different.

File: companion/src/mainwindow.cpp [hunk 2]
```diff
@@ -1294,92 +1298,109 @@ bool MainWindow::convertEEPROM(QString backupFile, QString restoreFile, QString
...
+      if (!readFirmwareFromRadio(tempFlash)) {
+        QMessageBox::warning(this, tr("Firmware check failed"), tr("Could not check firmware from radio"));
+        return;
+      }
+      FlashInterface previousFlash(tempFlash);
+      qunlink(tempFlash);
```
Comment (projectkk2glider) [inline companion/src/mainwindow.cpp]: Temp file deleted

File: companion/src/mainwindow.cpp [hunk 3]
```diff
@@ -1294,92 +1298,109 @@ bool MainWindow::convertEEPROM(QString backupFile, QString restoreFile, QString
...
+      FlashInterface newFlash(fileName);
+      qDebug() << "MainWindow::writeFlash(): checking firmware compatibility between " << tempFlash << "and" << fileName;
+      if (!newFlash.isHardwareCompatible(previousFlash)) {
+        QMessageBox::warning(this, tr("Firmware check failed"), tr("New firmware is not compatible with the one currently installed!"));
+        if (isTempFileName(fileName)) {
+          qDebug() << "MainWindow::writeFlash(): removing temporary file" << fileName;
+          qunlink(fileName);
```
Comment (projectkk2glider) [inline companion/src/mainwindow.cpp]: Temp file deleted

File: companion/src/mainwindow.cpp [hunk 4]
```diff
@@ -1294,92 +1298,109 @@ bool MainWindow::convertEEPROM(QString backupFile, QString restoreFile, QString
...
+        QString backupFile = backupPath+"/backup-"+QDateTime().currentDateTime().toString("yyyy-MM-dd-hhmmss")+".bin";
+        readEepromFromRadio(backupFile, tr("Backup Models and Settings From Radio"));
+        sleep(2);
       }
+
+      writeFirmwareToRadio(fileName);
+    }
+    if (isTempFileName(fileName)) {
+      qDebug() << "MainWindow::writeFlash(): removing temporary file" << fileName;
+      qunlink(fileName);
```
Comment (projectkk2glider) [inline companion/src/mainwindow.cpp]: Temp file deleted

**Comment by projectkk2glider** [comment]
I have now tested this on real radio (in Linux). All cases are working now. Since @bsongis is not around, I will self-merge this to master and make a nighly build for testers.

**Comment by bsongis** [comment]
Yes go on I am still not at home !

**Comment by bsongis** [comment]
I was mistaken by the function which doesn't provide a unique filename. I
think it should be fixed as well to avoid it happens again...

**Comment by projectkk2glider** [comment]
>I was mistaken by the function which doesn't provide a unique filename.

I wrote the function `generateProcessUniqueTempFileName()` and gave it such long name  precisely to avoid this kind of confusion.
