### PR TITLE
[Companion] Fix conversion of switches between X7 and X9/10/12 radios.

### LINKED ISSUE #5408: SH no converted in logical switchs.
SH switch is the same in X9D+ and QX7 transmiter, when any Companion file is converted from X9D+ to QX7, the SH switch not is converted.
For example, it is not converted in mixes or logical switches page.

### PR DESCRIPTION
**Pull request by mpaperno**
Also sources in Inputs were not getting converted at all (only in Mixes).

Closes #5408 

Note/discuss: When converting to X7, `SE` and `SG` both get converted to `SD` (for sources and switches). Because they are all 3-position types.  Previously it was (attempting to) convert `SG` to `SF` which is awkward because SF is only 2-pos (at least for switches... would be OK for sources but seems better to be consistent).

Round-trip conversion after these fixes:
x7-switch-conversions

Before fixes, X9E to X7 conversion:
x7-switch-conversions-old

Before fixes, X7 to X9E conversion:
x7-switch-conversions-old-tox9

### CODE REVIEW

File: companion/src/radiodata.cpp [hunk 1]
```diff
@@ -39,61 +39,97 @@ RawSource RawSource::convert(Board::Type before, Board::Type after)
...
 RawSwitch RawSwitch::convert(Board::Type before, Board::Type after)
 {
+  if (!index || type != SWITCH_TYPE_SWITCH) {
+    return *this;  // no changes
+  }
+
   // SWI to SWR don't exist on !X9E board
   if (!IS_TARANIS_X9E(after) && IS_TARANIS_X9E(before)) {
-    if (type == SWITCH_TYPE_SWITCH && index >= 24) {
+    if (abs(index) > 24) {
```
Comment (opentx-sonar) [inline companion/src/radiodata.cpp]: MAJOR Merge this if statement with the enclosing one. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1066)

File: companion/src/radiodata.cpp [hunk 2]
```diff
@@ -39,61 +39,97 @@ RawSource RawSource::convert(Board::Type before, Board::Type after)
...
-  // No S3, LS and RS on X7 board
-  if (IS_TARANIS_X7(after)) {
-    if (type == SOURCE_TYPE_STICK && index >= 6) {
-      index = 5;
-    }
-  }
-
   // SWI to SWR don't exist on !X9E board
   if (!IS_TARANIS_X9E(after) && IS_TARANIS_X9E(before)) {
     if (type == SOURCE_TYPE_SWITCH && index >= 8) {
```
Comment (opentx-sonar) [inline companion/src/radiodata.cpp]: MAJOR Merge this if statement with the enclosing one. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1066)

**Comment by opentx-sonar** [comment]
SonarQube analysis reported 9 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 7 major
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 7 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [radiodata.cpp#L26](https://github.com/opentx/opentx/blob/ec0225cb31363b1175462595e1181a6df55325eb/companion/src/radiodata.cpp#L26): Refactor this function to reduce its Cognitive Complexity from 32 to the 25 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS3776)
1. ![MAJOR][MAJOR] [radiodata.cpp#L34](https://github.com/opentx/opentx/blob/ec0225cb31363b1175462595e1181a6df55325eb/companion/src/radiodata.cpp#L34): Merge this if statement with the enclosing one. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1066)
1. ![MAJOR][MAJOR] [radiodata.cpp#L35](https://github.com/opentx/opentx/blob/ec0225cb31363b1175462595e1181a6df55325eb/companion/src/radiodata.cpp#L35): Merge this if statement with the enclosing one. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1066)
1. ![MAJOR][MAJOR] [radiodata.cpp#L208](https://github.com/opentx/opentx/blob/ec0225cb31363b1175462595e1181a6df55325eb/companion/src/radiodata.cpp#L208): Merge this if statement with the enclosing one. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1066)
1. ![MAJOR][MAJOR] [radiodata.cpp#L241](https://github.com/opentx/opentx/blob/ec0225cb31363b1175462595e1181a6df55325eb/companion/src/radiodata.cpp#L241): Merge this if statement with the enclosing one. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1066)
1. ![MAJOR][MAJOR] [radiodata.cpp#L272](https://github.com/opentx/opentx/blob/ec0225cb31363b1175462595e1181a6df55325eb/companion/src/radiodata.cpp#L272): Extract the assignment from this expression. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AAssignmentInSubExpression)
1. ![INFO][INFO] [radiodata.cpp#L24](https://github.com/opentx/opentx/blob/ec0225cb31363b1175462595e1181a6df55325eb/companion/src/radiodata.cpp#L24): Complete the task associated to this "TODO" comment. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1135)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by bsongis** [comment]
Thanks!

**Comment by bsongis** [comment]
SE and SG both get converted to SD (for sources and switches) => it is good!
