### PR TITLE
Companion wizard fixes

### LINKED ISSUE #6449: Companion model wizard name corruption
Model Wizard 1

Model Wizard Corruption
**General information**
- OpenTX Companion (2.3 tool chain)
- Radio Profile: X-Lite
- Ubuntu 14.04

### PR DESCRIPTION
**Pull request by elecpower**
Fixes #6449 
Fixes throttle timer not being created
Add names to timers

### CODE REVIEW

File: companion/src/wizarddata.cpp [hunk 1]
```diff
@@ -102,7 +102,7 @@ WizMix::operator ModelData()
 
   // Safe copy model name
   strncpy(model.name, name, WIZ_MODEL_NAME_LENGTH);
```
Comment (bsongis) [inline companion/src/wizarddata.cpp]: I would rather see you memset the model.name array to 0

File: companion/src/wizarddialog.cpp [hunk 2]
```diff
@@ -307,7 +307,7 @@ bool ModelSelectionPage::validatePage()
   newName = (newName.normalized(QString::NormalizationForm_D));
   newName = newName.replace(QRegExp("[^ A-Za-z0-9_.-,\\s]"), "");
   strncpy( wizDlg->mix.name, newName.toLatin1(), WIZ_MODEL_NAME_LENGTH);
-  wizDlg->mix.name[WIZ_MODEL_NAME_LENGTH] = 0;
```
Comment (bsongis) [inline companion/src/wizarddialog.cpp:310]: same comment here

**Comment by bsongis** [comment]
Same comment many times: 
you could memset the whole name array to 0

**Comment by bsongis** [comment]
Thanks!
