### PR TITLE
Fix GPS display in telem screen for X9. 

### LINKED ISSUE #4382: N362@X9 GPS coord. alignment in 3 column telemetry screen (cosmetics)
GPS degrees are cut off
attachment
Seconds wiped out by me

### PR DESCRIPTION
**Pull request by 3djc**
With this fix, it is working fine, but maybe could be improved later by moving to right aligned

image

X7:
image

This closes #4382

### CODE REVIEW

**Comment by bsongis** [comment]
There is no vertical bar on the 128x64 telemetry screens? I thought there was one!

**Comment by 3djc** [comment]
Yes, already discussed with @kilrah, it seems to be there sometime, and sometimes not, will investigate (but this should be unrelated)

File: radio/src/gui/128x64/lcd.cpp [hunk 1]
```diff
@@ -1119,6 +1119,7 @@ void drawValueWithUnit(coord_t x, coord_t y, lcdint_t val, uint8_t unit, LcdFlag
 
 void drawGPSCoord(coord_t x, coord_t y, int32_t value, const char * direction, LcdFlags att, bool seconds=true)
 {
+  att &= ~RIGHT & ~BOLD;
```
Comment (bsongis) [inline radio/src/gui/128x64/lcd.cpp]: wow is it easy to understand? I am rather used to `att &= ~(RIGHT|BOLD)`

**Comment by kilrah** [comment]
> There is no vertical bar on the 128x64 telemetry screens? I thought there was one!

Supposed to be, but it broke somehow...
