### PR TITLE
Fix LUA telemetry (+/-/exit handling)

### LINKED ISSUE #7309: Multiple Screens navigation with +/- breaks Betaflight menu navigation
If the betaflight LUA scripts are installed, and enabled in a model's DISPLAY settings on one screen as type 'script' and on another screen a type of 'num' is selected to display telemetry information, then every +/- key press whilst in the betaflight menus causes the displayed screen to also change.

It would appear that the +/- buttons have been configured to switch between the screens, which used to be done by pressing the PAGE button.

Steps to reproduce:
Install Betaflight LUA scripts as per https://github.com/betaflight/betaflight-tx-lua-scripts

1. Navigate to DISPLAY screen for a given model
2. Set Screen 1 to "Script bf"
3. Set Screen 2 to "Nums" and add an arbitrary data field to display
4. Press EXIT
5. Press and hold PAGE - the Betaflight menus should appear
6. Press + or - and instead of moving in the menu as expected, screen 2 will appear

If Screen 2 is not configured, then the menus operate as expected.

**General information**
 - OpenTX version: 2.3.5
 - Hardware: Frsky X9D+
 - OpenTX Companion: 2.3 on MacOS

### LINKED ISSUE #7335: +/- changes the telemetry screen on Taranis X9D
Pressing the +/- buttons changes telemetry screens on X9D and plus, in addition to the PAGE button. This completely screws up Lua scripts that use these buttons, e.g. my SoarOTX programs.
https://github.com/jfrickmann/SoarOTX/wiki
Please remove that "feature" immediately!!!

Sincerely,
Jesper Frickmann

### LINKED ISSUE #7351: LUA Script Menu - exit key closes the whole script
252/5000
OpenTX 2.3.5
Taranis X9D +
yaapu / FrskyTelemetryScript

The script works great, but if I want to exit the Lua menu with the Exit button, it always closes the whole script.
  In OpenTX 2.3.1 everything is still in order (schort an long press exit).
Is this a bug in opentx?

### PR DESCRIPTION
**Pull request by 3djc**
This fixes #7351 
This fixes #7335 
This fixes #7309 

This closes #7348

### CODE REVIEW

File: radio/src/gui/common/stdlcd/view_telemetry.cpp [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+void menuViewTelemetry(event_t event)
+{
+  enum NavigationDirection direction = none;
+
+  if (event == EVT_KEY_FIRST(KEY_EXIT) && TELEMETRY_SCREEN_TYPE(s_frsky_view) != TELEMETRY_SCREEN_TYPE_SCRIPT) {
+    killEvents(event);
+    chainMenu(menuMainView);
+  }
+#if defined(LUA)
+    else if (event == EVT_KEY_LONG(KEY_EXIT)) {
```
Comment (bsongis) [inline radio/src/gui/common/stdlcd/view_telemetry.cpp]: indentation

File: radio/src/gui/common/stdlcd/view_telemetry.cpp [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+ * GNU General Public License for more details.
+ */
+
+#include "opentx.h"
+
+extern bool displayTelemetryScreen();
+extern void displayRssiLine();
+
+enum NavigationDirection {
+  none,
```
Comment (bsongis) [inline radio/src/gui/common/stdlcd/view_telemetry.cpp]: uppercase with more explicit labels

File: radio/src/gui/common/stdlcd/view_telemetry.cpp [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+  up,
```
Comment (bsongis) [inline radio/src/gui/common/stdlcd/view_telemetry.cpp]: like NAVIGATION_DIRECTION_UP
