### PR TITLE
Various fixes around Companion trainer mode

### LINKED ISSUE #7091: [Companion 2.3.2N44] Missing the "Multi-Trainer" option in the "Trainer" menu
The picture shows the lack of the "Multi-Trainer" option in the drop-down menu of "Trainer".

  - OpenTX Companion V2.3.2 N44

multitrainer

### PR DESCRIPTION
**Pull request by 3djc**
This fixes #7091

### CODE REVIEW

File: companion/src/modeledit/setup.cpp [hunk 1]
```diff
@@ -198,10 +198,21 @@ ModulePanel::ModulePanel(QWidget * parent, ModelData & model, ModuleData & modul
     if (IS_HORUS(firmware->getBoard())) {
```
Comment (bsongis) [inline companion/src/modeledit/setup.cpp]: !IS_TARANIS(...)
