### PR TITLE
Several Lua improvements for stability

### LINKED ISSUE #3885: An error in Lua widget should not disable Lua globally
Such erorr should only disable the offending widget.

Test case:

``` lua
local options = {
    "kill Lua",
}

function create(zone, options)
    local context = { zone=zone, options=options }
    return context
end

function update(context, options)
    context.options = options
end

function refresh(context)
    lcd.drawText(context.zone.x, context.zone.y, "Val: " .. context.options.Val)
end

return { name="Test", options=options, create=create, update=update, refresh=refresh }
```

Result of above script is:

```
PANIC: unprotected error in call to Lua API (bad argument #-1 (table expected, got string))
```

resulting from the failed `luaL_checktype()`

### PR DESCRIPTION
**Pull request by projectkk2glider**
Lua: Use incremental GC and also call it for Widgets
Fixes #3885: Error in Lua Widget options handled better (does not disable entire Lua state)
Disable Lua Widget if any of its functions has error.

This is a rough concept:
 * if a widget has Lua erorr, remember error and disable offending widget (it is still availabe in factory, should it be removed from there also?)
 * show widget error to user in widget settings screen   (very rough, should be improved visually)
 * I thought GC was running in Lua automagically, looks like it is not, lua_gc() call is needed, this commit also fixes this. The Scripts are also not GC so aggressively now (was always full GC). Needs testing and tuning (amount of work for incremental GC can be tuned).
 * Added a variable that keeps the total value of memory used by bitmaps that were loaded from withing Lua. This will enable Lua script memory usage limiting. See #4284 

Further ideas for this PR:
 * add Lua debug buffer (Horus only) which would store last N lua outputs (errors from interpreter and print()), Create a new screen that will display this buffer and allow user to scroll trough it. Options: save to file, clear.
 * Implement #4284

### CODE REVIEW

**Comment by projectkk2glider** [comment]
None of this was tested on actual radio :stuck_out_tongue_closed_eyes: only in `simu`

**Comment by kellybyrd** [comment]
This seems reasonable at first glance.

File: radio/src/gui/480x272/screens_setup.cpp [hunk 1]
```diff
@@ -176,6 +176,23 @@ int getOptionsCount(const ZoneOption * options)
 template <class T>
 bool menuSettings(const char * title, const T * object, uint32_t i_flags, event_t event)
 {
+
+  if (object->getErrorMessage()) {
+    // display error instead of widget settings
+    // TODO nicer display (proper word-wrap)
```
Comment (bsongis) [inline radio/src/gui/480x272/screens_setup.cpp]: Right we could add another flag in LcdFlags for this

File: radio/src/lua/widgets.cpp [hunk 2]
```diff
@@ -385,8 +427,8 @@ void luaLoadFile(const char * filename, void (*callback)())
     }
   }
   else {
-    // luaDisable();
-    lsWidgets = 0;
+    // error while loading Lua widget/theme,
+    // do not disable whole Lua state, just ingnore bad widget/theme
```
Comment (bsongis) [inline radio/src/lua/widgets.cpp]: typo

**Comment by bsongis** [comment]
Yes it seems good. I am only afraid that we will have problems with Taranis where the GC is very sensible!

**Comment by projectkk2glider** [comment]
>I am only afraid that we will have problems with Taranis where the GC is very sensible!

Should not be a problem in my opinion. Lua will do an emergency full GC every time it fails to allocate a new chunk of memory and fails, then it tries to allocate second time - this should take care of your concerns.

**Comment by bsongis** [comment]
I didn't know this, thanks for the info!
