### PR TITLE
Fix custom scripts outputs handling

### LINKED ISSUE #5546: 2.2.1 Mix Scripts Custom Screen X7 Not showing all outputs
2.2.1 Companion
Mix Scripts
Simulator
Custom Scripts
Scripts selected "Sqnc"
Problem
X7 Outputs shows only 1 of 2
X9D Outputs shows both
Anone reported this?
Not all outputs showing for mix scripts on X7
screenshot_x9d_17-12-19_11-04-24

screenshot_x7_17-12-19_11-05-50

### PR DESCRIPTION
**Pull request by 3djc**
One output was missing if there where inputs lines
Scrolling was making a pause at Outputs label

This fixes #5546

### CODE REVIEW

File: radio/src/gui/128x64/model_custom_scripts.cpp [hunk 1]
```diff
@@ -61,7 +61,7 @@ void menuModelCustomScriptOne(event_t event)
   drawStringWithIndex(PSIZE(TR_MENUCUSTOMSCRIPTS)*FW+FW, 0, "LUA", s_currIdx+1, 0);
   lcdDrawFilledRect(0, 0, LCD_W, FH, SOLID, 0);
 
-  SUBMENU(STR_MENUCUSTOMSCRIPTS, 3+scriptInputsOutputs[s_currIdx].inputsCount+scriptInputsOutputs[s_currIdx].outputsCount, { 0, 0, LABEL(inputs), 0/*repeated*/ });
+  SUBMENU(STR_MENUCUSTOMSCRIPTS, 3+scriptInputsOutputs[s_currIdx].inputsCount+scriptInputsOutputs[s_currIdx].outputsCount + 1 /*outputs label*/, { 0, 0, LABEL(inputs), 0/*repeated*/ });
```
Comment (bsongis) [inline radio/src/gui/128x64/model_custom_scripts.cpp]: Would you use the HEADER_LINE constant here?
