### PR TITLE
Fixes #5402

### LINKED ISSUE #5402: Companion 2.2.1 build 440: UI bug during eeprom translation from X9D to QX7
The problem arises in Companion 2.2.1 (latest nightly build) after translating a model to QX7 format. If the model contains a mix with a source which is not supported by the QX7 (e.g. 'LS') then opening the mixer editor may cause subsequent mixers to dissappear.

Minimalist .otx file for the X9D is available [here](https://www.dropbox.com/s/3rj7bhe9um4jdgw/UI_Bug.otx?dl=0).

To reproduce the problem

1. Set the Companion profile to QX7
2. Open the X9D .otx. Data is translated in situ
3. Locate the 'LS' mixer line, and open the mixer editor

- If you change the source from 'LS' to a valid control for the QX7, there's no problem.
- However, if you press OK without changing to a valid source, all subsequent mixers are deleted.

### PR DESCRIPTION
**Pull request by bsongis**

### CODE REVIEW

File: companion/src/radiodata.cpp [hunk 1]
```diff
@@ -31,14 +31,21 @@ RawSource RawSource::convert(Board::Type before, Board::Type after)
   }
 
   if (IS_HORUS(after)) {
-    if (IS_TARANIS_X9D(before) || IS_TARANIS_X7(before)) {
+    if (IS_TARANIS_X9D(before)) {
```
Comment (opentx-sonar) [inline companion/src/radiodata.cpp]: MAJOR Merge this if statement with the enclosing one. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1066)

File: companion/src/radiodata.cpp [hunk 2]
```diff
@@ -31,14 +31,21 @@ RawSource RawSource::convert(Board::Type before, Board::Type after)
...
       if (type == SOURCE_TYPE_STICK && index >= 7) {
```
Comment (opentx-sonar) [inline companion/src/radiodata.cpp]: MAJOR Merge this if statement with the enclosing one. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1066)

File: companion/src/radiodata.cpp [hunk 3]
```diff
@@ -31,14 +31,21 @@ RawSource RawSource::convert(Board::Type before, Board::Type after)
...
+  // No S3, LS and RS on X7 board
+  if (IS_TARANIS_X7(after)) {
+    if (type == SOURCE_TYPE_STICK && index >= 6) {
+      index = 5;
+    }
+  }
+
   // SWI to SWR don't exist on !X9E board
   if (!IS_TARANIS_X9E(after) && IS_TARANIS_X9E(before)) {
     if (type == SOURCE_TYPE_SWITCH && index >= 8) {
```
Comment (opentx-sonar) [inline companion/src/radiodata.cpp]: MAJOR Merge this if statement with the enclosing one. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1066)

File: companion/src/radiodata.cpp [hunk 4]
```diff
@@ -31,14 +31,21 @@ RawSource RawSource::convert(Board::Type before, Board::Type after)
...
       if (type == SOURCE_TYPE_STICK && index >= 7) {
         // LS and RS on Horus are after sliders L1 and L2
         index += 2;
       }
     }
   }
 
+  // No S3, LS and RS on X7 board
+  if (IS_TARANIS_X7(after)) {
+    if (type == SOURCE_TYPE_STICK && index >= 6) {
```
Comment (opentx-sonar) [inline companion/src/radiodata.cpp]: MAJOR Merge this if statement with the enclosing one. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1066)

**Comment by opentx-sonar** [comment]
SonarQube analysis reported 12 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 10 major
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 8 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [radiodata.cpp#L26](https://github.com/opentx/opentx/blob/0f7e239dbc1654eeea8be60ca743d4bab61f84f0/companion/src/radiodata.cpp#L26): Refactor this function to reduce its Cognitive Complexity from 27 to the 25 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS3776)
1. ![MAJOR][MAJOR] [radiodata.cpp#L58](https://github.com/opentx/opentx/blob/0f7e239dbc1654eeea8be60ca743d4bab61f84f0/companion/src/radiodata.cpp#L58): Merge this if statement with the enclosing one. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1066)
1. ![MAJOR][MAJOR] [radiodata.cpp#L75](https://github.com/opentx/opentx/blob/0f7e239dbc1654eeea8be60ca743d4bab61f84f0/companion/src/radiodata.cpp#L75): Merge this if statement with the enclosing one. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1066)
1. ![MAJOR][MAJOR] [radiodata.cpp#L82](https://github.com/opentx/opentx/blob/0f7e239dbc1654eeea8be60ca743d4bab61f84f0/companion/src/radiodata.cpp#L82): Merge this if statement with the enclosing one. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1066)
1. ![MAJOR][MAJOR] [radiodata.cpp#L172](https://github.com/opentx/opentx/blob/0f7e239dbc1654eeea8be60ca743d4bab61f84f0/companion/src/radiodata.cpp#L172): Merge this if statement with the enclosing one. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1066)
1. ![MAJOR][MAJOR] [radiodata.cpp#L205](https://github.com/opentx/opentx/blob/0f7e239dbc1654eeea8be60ca743d4bab61f84f0/companion/src/radiodata.cpp#L205): Merge this if statement with the enclosing one. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1066)
1. ![MAJOR][MAJOR] [radiodata.cpp#L236](https://github.com/opentx/opentx/blob/0f7e239dbc1654eeea8be60ca743d4bab61f84f0/companion/src/radiodata.cpp#L236): Extract the assignment from this expression. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AAssignmentInSubExpression)
1. ![INFO][INFO] [radiodata.cpp#L24](https://github.com/opentx/opentx/blob/0f7e239dbc1654eeea8be60ca743d4bab61f84f0/companion/src/radiodata.cpp#L24): Complete the task associated to this "TODO" comment. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1135)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
