### PR TITLE
Fix lcd.drawRectangle on Horus

### LINKED ISSUE #3486: [Horus] lcd.drawRectangle force close on Horus

### PR DESCRIPTION
**Pull request by 3djc**
This fixes  lcd.drawRectangle force close on Horus. This changes also add a new extra mandatory field 'thickness' : doc will need to be updated accordingly

This fixes #3486

### CODE REVIEW

File: radio/src/lua/api_lcd.cpp [hunk 1]
```diff
@@ -367,6 +367,8 @@ Draw a rectangle from top left corner (x,y) of specified width and height
 
 @param flags (unsigned number) drawing flags
 
+@param t (number) thikness in pixels
```
Comment (projectkk2glider) [inline radio/src/lua/api_lcd.cpp]: thikness -> thickness

File: radio/src/lua/api_lcd.cpp [hunk 2]
```diff
@@ -377,7 +379,12 @@ static int luaLcdDrawRectangle(lua_State *L)
   int w = luaL_checkinteger(L, 3);
   int h = luaL_checkinteger(L, 4);
   unsigned int flags = luaL_optunsigned(L, 5, 0);
+  #if defined(PCBHORUS)
```
Comment (projectkk2glider) [inline radio/src/lua/api_lcd.cpp]: Un-indent please, same goes for other two `#if #else #endif` lines.

File: radio/src/lua/api_lcd.cpp [hunk 3]
```diff
@@ -377,7 +379,12 @@ static int luaLcdDrawRectangle(lua_State *L)
...
+  int t = luaL_optinteger(L, 6, 0);
```
Comment (projectkk2glider) [inline radio/src/lua/api_lcd.cpp]: The `thickness` parameter is unsigned, so I would prefer `unsigned int t =  tluaL_optunsigned()`

Comment (3djc) [inline radio/src/lua/api_lcd.cpp]: Indeed, changes pushed :)

**Comment by bsongis** [comment]
Thanks!
