### PR TITLE
Fix FM screen on X7

### LINKED ISSUE #4513: Cannot edit FM0 GVar 6,7,8,9  and FM1-9 GVar 9 on Q-X7
OpenTX 2.2 RC10
The problem is observable on the Radio and the Companion Simulator.

In FM0 editor the Scroll wheel jumps past the value field of GV6 straight to the GV7 name field and then jumps past the GV7 value field.  It does not scroll GV8 an GV9 into view but jumps to the top of the FM0 fields.
FM1 thru FM 8 can edit GV6,7 and 8 but will not scroll GV9 into view.  It jumps to the top of the FM fields.

The simulator in Companion shows the same behavior.

### PR DESCRIPTION
**Pull request by 3djc**
While it checks ok on sime and radio, please review thoroughly the changes
This fixes #4513

### CODE REVIEW

File: radio/src/gui/128x64/model_flightmodes.cpp [hunk 1]
```diff
@@ -92,14 +92,14 @@ void menuModelPhaseOne(event_t event)
...
-  static const pm_uint8_t mstate_tab_fm1[] PROGMEM = {0, 3, 0, 0, (uint8_t)-1, 1, 1, 1, 1, 1};
+  static const pm_uint8_t mstate_tab_fm1[] PROGMEM = {0, 3, 0, 0, (uint8_t)-1, 1, 1, 1, 1, 1, 1};
 #else // PCBX7
   #define VERTICAL_SHIFT  (ITEM_MODEL_PHASE_FADE_IN-ITEM_MODEL_PHASE_SWITCH)
   static const pm_uint8_t mstate_tab_fm1[] PROGMEM = {0, 0, 0, (uint8_t)-1, 1, 1, 1, 1, 1};
 #endif // PCBX7
   static const pm_uint8_t mstate_tab_others[] PROGMEM = {0, 0, 3, IF_ROTARY_ENCODERS(NUM_ROTARY_ENCODERS-1) 0, 0, (uint8_t)-1, 2, 2, 2, 2, 2};
 
-  check(event, 0, NULL, 0, (s_currIdx == 0) ? mstate_tab_fm1 : mstate_tab_others, DIM(mstate_tab_others)-1, ITEM_MODEL_PHASE_MAX - 1 - (s_currIdx==0 ? (ITEM_MODEL_PHASE_FADE_IN-ITEM_MODEL_PHASE_SWITCH) : 0));
+  check(event, 0, NULL, 0, (s_currIdx == 0) ? mstate_tab_fm1 : mstate_tab_others, DIM(mstate_tab_others)-1, ITEM_MODEL_PHASE_MAX  - (s_currIdx==0 ? (ITEM_MODEL_PHASE_FADE_IN-ITEM_MODEL_PHASE_SWITCH-1) : 0));
```
Comment (bsongis) [inline radio/src/gui/128x64/model_flightmodes.cpp]: I am afraid this `-1` is needed on 9XR-PRO
I think you need `- HEADER_LINE` as done on some other files

Comment (3djc) [inline radio/src/gui/128x64/model_flightmodes.cpp]: Done it, simu tested ok (I think) on 9XR-PRO (and X7 also)

**Comment by bsongis** [comment]
It remains a problem, I will take it now
