### PR TITLE
Show 9 gvars on 9x radios - Fixes 7678

### LINKED ISSUE #7678: 9x radios showing too many gvars
**Describe the bug**
Flight mode menu is showing 10 gvars

**To Reproduce**
1. Go to _Flight mode_ menu
2. Scroll down
3. See error

**Expected behavior**
Show 9 gvars

**General information**
 - OpenTX version 2.3.7
 - Hardware (9X Pro)

### LINKED ISSUE #7698: 2.3.7 bootloader does not allow connection to OpenTX companion in Mac OSX Catalina
**Describe the bug**
I have updated firmware and bootloader on my Taranis XD9+ to 2.3.7. Since the update I cannot connect to it with OpenTX companion.
df-util cannot list my Taranis, after I turn my Taranis on, set it to communication mode by turning it on holding the bottom trim buttons to the center and connecting via USB.

```
/Applications/OpenTX\ Companion\ 2.3.app/Contents/Resources/dfu-util -l
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/
```

And OpenTx Companion complains that there are no transmitter connected.
In the syslog I see the following

```
sudo dmesg |grep Taranis
USB device 0483572014300000 - FrSky, FrSky Taranis Bootloader - detected termination of interfaceNub, currentPowerState 1, provider is non-NULL
```
Interestingly,  setting up Taranis in bootloader mode, I get the correct output from df-util

```
/Applications/OpenTX\ Companion\ 2.3.app/Contents/Resources/dfu-util -l
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Found DFU: [0483:df11] ver=2200, devnum=10, cfg=1, intf=0, path="20-3", alt=3, name="@Device Feature/0xFFFF0000/01*004 e", serial="207F36803548"
Found DFU: [0483:df11] ver=2200, devnum=10, cfg=1, intf=0, path="20-3", alt=2, name="@OTP Memory /0x1FFF7800/01*512 e,01*016 e", serial="207F36803548"
Found DFU: [0483:df11] ver=2200, devnum=10, cfg=1, intf=0, path="20-3", alt=1, name="@Option Bytes  /0x1FFFC000/01*016 e", serial="207F36803548"
Found DFU: [0483:df11] ver=2200, devnum=10, cfg=1, intf=0, path="20-3", alt=0, name="@Internal Flash  /0x08000000/04*016Kg,01*064Kg,07*128Kg", serial="207F36803548"
```
But, still OpenTX companion cannot connect to it

I tried on two different Macbooks, and I get the same behavior. Very same.

**General information**
 - OpenTX 2.3.7
- Bootloader 2.3.7
 - Hardware Frsky Taranis XD9+
 - OpenTX Companion 2.3.7 on Mac OSX 10.15.5 Catalina

### PR DESCRIPTION
**Pull request by dgatf**
Fixes #7678 

Show 9 gvars instead of 10 in edit flight mode menu for 9x radios

### CODE REVIEW

File: radio/src/gui/128x64/model_flightmodes.cpp [hunk 1]
```diff
@@ -73,7 +73,11 @@ void menuModelFlightModeOne(event_t event)
 #endif
   static const uint8_t mstate_tab_others[]  = {0, 0, 3, 0, 0, (uint8_t)-1, 2, 2, 2, 2, 2};
 
-  check(event, 0, NULL, 0, (s_currIdx == 0) ? mstate_tab_fm1 : mstate_tab_others, DIM(mstate_tab_others)-1, ITEM_MODEL_FLIGHT_MODE_MAX - HEADER_LINE - (s_currIdx==0 ? (ITEM_MODEL_FLIGHT_MODE_FADE_IN-ITEM_MODEL_FLIGHT_MODE_SWITCH-1) : 0));
+#if defined(PCBSKY9X)
+  check(event, 0, NULL, 0, (s_currIdx==0) ? mstate_tab_fm1 : mstate_tab_others, DIM(mstate_tab_others)-1, ITEM_MODEL_FLIGHT_MODE_MAX-HEADER_LINE-1-(s_currIdx==0 ? (ITEM_MODEL_FLIGHT_MODE_FADE_IN-ITEM_MODEL_FLIGHT_MODE_SWITCH-1) : 0));
```
Comment (3djc) [inline radio/src/gui/128x64/model_flightmodes.cpp]: Cosmetics (spaces missings)
Not sure the fix is right tho, if you edit on FM0, trims line is missing

Comment (dgatf) [reply radio/src/gui/128x64/model_flightmodes.cpp]: Yes, that's weird, trims for fm0 were missing already... that's why it was showing an additional gvar. Fixed
