### PR TITLE
3djc/horus checklist improvement

### LINKED ISSUE #4190: Horus calling the texts  .txt for a model does not work
Problem with OpenTx Horus

For each model, a note can be displayed at startup. This works only with the first model.
Next model no more

Raimund

### PR DESCRIPTION
**Pull request by 3djc**
- current way of working (like Taranis stays)
- in addition to that, you will also be able to use the modelxx.txt (even if your plane is called 'MySuperPlane')
- in case both are present (you should not be doing that, but just in case), the taranis style will have priority

This fixes #4190

### CODE REVIEW

File: radio/src/gui/gui_common_arm.cpp [hunk 1]
```diff
@@ -568,7 +568,18 @@ bool modelHasNotes()
   char filename[sizeof(MODELS_PATH)+1+sizeof(g_model.header.name)+sizeof(TEXT_EXT)] = MODELS_PATH "/";
   char *buf = strcat_currentmodelname(&filename[sizeof(MODELS_PATH)]);
   strcpy(buf, TEXT_EXT);
+#if defined(PCBHORUS)
+  if (isFileAvailable(filename)) {
```
Comment (bsongis) [inline radio/src/gui/gui_common_arm.cpp]: I would keep this if for all boards

File: radio/src/gui/gui_common_arm.cpp [hunk 2]
```diff
@@ -568,7 +568,18 @@ bool modelHasNotes()
...
+    return true;
+  }
+  else {
```
Comment (bsongis) [inline radio/src/gui/gui_common_arm.cpp]: ... and here this block could go in `#if !defined(EEPROM)`

**Comment by bsongis** [comment]
excellent, thanks!
