### PR TITLE
Companion : fix channel numbers

### LINKED ISSUE #6927: Companion : wrong channel number limit for LR12
Actually, probably wrong for many protocols

### PR DESCRIPTION
**Pull request by 3djc**
This fixes #6927

### CODE REVIEW

File: companion/src/modeledit/setup.cpp [hunk 1]
```diff
@@ -366,6 +366,48 @@ void ModulePanel::setupFailsafes()
   lock = false;
 }
 
+int ModulePanel::getMaxChannelCount()
+{
+  const PulsesProtocol protocol = (PulsesProtocol)module.protocol;
+  switch (protocol) {
+    case PULSES_PXX_R9M:
```
Comment (kilrah) [inline companion/src/modeledit/setup.cpp:375]: Sure of that one?
