### PR TITLE
Fixes #2123: lcd_bmp() could write outside the LCD buffer

### LINKED ISSUE #2123: [BUG] after lcd.drawPixmap event EVT_PAGE_BREAK is sometime generated automaticaly
This is a funny bug !

Bug found in the simulator V2.0.15 (not tested yet on the Taranis)

I found that when you draw a bitmap too big for the screen, it can in some circumstance generate automaticaly a EVT_PAGE_BREAK event.

Here is a standalone script to reproduce the bug : 

    local col = 149 -- Error will occur at col 152
    local time = getTime()
    local bingo = false -- True when the bug occurs
    
    local function run(event)
      if not bingo then print("Event :", event) end
      lcd.lock()
      if event == nil then
        error("Cannot be run as a model script!")
        return 2
      elseif event == EVT_EXIT_BREAK then
        return 2
      elseif event == 0 then
        if not bingo and (getTime() - time) % 100 == 0 then
          lcd.clear()
          col = col + 1
          lcd.drawPixmap(col, 1, "/SCRIPTS/bugpixmap.bmp") -- height : 65 pixel, width 1 pixel 
          lcd.drawText(1, 11, "At col : ", 0)
          lcd.drawNumber(lcd.getLastPos(), 11, col, LEFT)
        end
      elseif event == 189 then
        lcd.clear()
        col = col + 1
        lcd.drawPixmap(col, 1, "/SCRIPTS/bugpixmap.bmp") -- height : 64 pixel, width 1 pixel 
        lcd.drawText(1, 11, "At col : ", 0)
        lcd.drawNumber(lcd.getLastPos(), 11, col, LEFT)
      elseif event == EVT_PAGE_BREAK then
        bingo = true
        print("Bingo")
        lcd.drawText(1, 1, "Bingo", 0)
        lcd.drawText(1, 11, "At col : ", 0)
        lcd.drawNumber(lcd.getLastPos(), 11, col, LEFT)
        lcd.drawText(1, 21, "Event : ", 0)
        lcd.drawNumber(lcd.getLastPos(), 21, event, LEFT)
      end
      return 0
    end
    --
    return {run=run}

And here is the image used by the script (it's a PNG that must be converted as BMP to test the script) :  bugpixmap

The script trace the event flow in the console.

### PR DESCRIPTION
**Pull request by projectkk2glider**

### CODE REVIEW

File: radio/src/lcd_taranis.cpp [hunk 1]
```diff
@@ -66,9 +65,7 @@ void lcd_plot(xcoord_t x, uint8_t y, LcdFlags att)
 {
   uint8_t *p = &displayBuf[ y / 2 * LCD_W + x ];
   uint8_t mask = PIXEL_GREY_MASK(y, att);
-  if (p<DISPLAY_END) {
-    lcd_mask(p, mask, att);
```
Comment (projectkk2glider) [inline radio/src/lcd_taranis.cpp]: Duplicate check removed, it is already in lcd_mask()

**Comment by bsongis** [comment]
Thanks! Would you port it to 'next'?

**Comment by projectkk2glider** [comment]
Done in #2131 :)
