### PR TITLE
Fix mixer overflow

### LINKED ISSUE #7623: Flight mode transition bug
Another RCG user posted a problem he was having.
I looked at his OTX, and it seems like a bug to me in how flight mode transitions are done when a mixer channel is over +/-200.  The value changes sign and is offset by the difference from 200 during the transition.

Simple OTX attached, only one mixer line and one flight mode.  Channel value changes sign during flight mode transition, even though flight mode change should not affect its value at all.

### PR DESCRIPTION
**Pull request by dgatf**
Fixes mixer overflow #7623 by limiting the chans values when fading flightmodes

Added two non regresion tests for mixer modes transitions:

- _flightModeOverflow_ evaluates the initial overflow error (where current mixer fails) 
- _flightModeTransition_ evaluates the transition between two values (where dynamic bit shift fails)

### CODE REVIEW

File: radio/src/tests/gtests.h [hunk 1]
```diff
@@ -65,6 +65,7 @@ inline void MODEL_RESET()
   memset(&anaInValues, 0, sizeof(anaInValues));
   extern uint8_t s_mixer_first_run_done;
   s_mixer_first_run_done = false;
+  evalMixes(1);  // this is needed to reset fp_act
```
Comment (dgatf) [inline radio/src/tests/gtests.h:68]: needed to reset static variable fp_act

**Review by bsongis — APPROVED** [review]
