### PR TITLE
Issue #5696

### LINKED ISSUE #5696: GV limits wrong when trim is reused
When I use a special function to adjust a GV with a trim button, then limits for the trim are applied, where limits for the GV should  be applied instead.
I have attached an OTX to test the issue. Use A up or down to adjust GVs with TrmR and TrmA, I have removed the other files, as I created a pull request.

Jesper

[Test.otx.zip](https://github.com/opentx/opentx/files/1733618/Test.otx.zip)

### PR DESCRIPTION
**Pull request by jfrickmann**
When an "Adjust GV" special function is reusing trim buttons to increase/decrease GVs, then the trim limits are applied instead of GV limits. This patch applies the GV limits.

This fixes #5696

### CODE REVIEW

**Comment by bsongis** [comment]
Seems good but I need to take a coffee and take time on it before pressing the button

**Comment by jfrickmann** [comment]
Good to hear! I was wondering if we should also make the increment/decrement equal to 1 for GV, independently of trimInc? E.g. right after line 1362:
    if (thro) v = 4; // if throttle trim and trim trottle then step=4
insert:
#if defined(GVARS)
    if (TRIM_REUSED(idx)) v = 1;
#endif

**Comment by jfrickmann** [comment]
So, how was the coffee? :-)

File: radio/src/opentx.cpp [hunk 1]
```diff
@@ -1369,35 +1369,58 @@ uint8_t checkTrim(event_t event)
...
-    if (after > TRIM_EXTENDED_MAX) {
-      after = TRIM_EXTENDED_MAX;
-    }
 
 #if defined(GVARS)
     if (TRIM_REUSED(idx)) {
-      SET_GVAR_VALUE(trimGvar[idx], phase, after);
+      int8_t gvar = trimGvar[idx];
+#if defined(CPUARM)
+// TODO: This was necessary to make it compile for AVR9X target - maybe there is a better solution?
```
Comment (bsongis) [inline radio/src/opentx.cpp]: There is no MIN and MAX on GVARS on AVR9X
The comment may be removed

**Review by bsongis — APPROVED** [review]
Good job, I think everything is right

**Review by jfrickmann — COMMENTED** [review]
I have removed the comment as suggested, and added the lines that I suggested above in 1363-65.

File: radio/src/opentx.cpp [hunk 2]
```diff
@@ -1360,6 +1360,9 @@ uint8_t checkTrim(event_t event)
     int8_t trimInc = g_model.trimInc + 1;
     int8_t v = (trimInc==-1) ? min(32, abs(before)/4+1) : (1 << trimInc); // TODO flash saving if (trimInc < 0)
     if (thro) v = 4; // if throttle trim and trim trottle then step=4
+#if defined(GVARS)
+    if (TRIM_REUSED(idx)) v = 1;
```
Comment (bsongis) [inline radio/src/opentx.cpp:1364]: yes, exact

**Comment by bsongis** [comment]
Merged, thanks for your help!
