### PR TITLE
Fixes #2084: wrong constant used to limit maximum number of expos

### LINKED ISSUE #2084: Can't add new input with Lua model.insertInput()
Test script:
```lua
local function run(event)
  local ivalue={name="test", source=MIXSRC_Thr, weight=55, offset=3}
  model.insertInput(6, 0, ivalue)
  return 1
end

return {run=run}
```

### PR DESCRIPTION
**Pull request by projectkk2glider**
This should fix the problem described in https://github.com/opentx/opentx/issues/2084#issuecomment-102593774

### CODE REVIEW

File: radio/src/lua.cpp [hunk 1]
```diff
@@ -689,7 +689,7 @@ static int luaModelInsertInput(lua_State *L)
   unsigned int first = getFirstInput(chn);
   unsigned int count = getInputsCountFromFirst(chn, first);
 
-  if (chn<MAX_INPUTS && getExpoMixCount(1)<MAX_INPUTS && idx<=count) {
+  if (chn<MAX_INPUTS && getExpoMixCount(1)<MAX_EXPOS && idx<=count) {
```
Comment (bsongis) [inline radio/src/lua.cpp]: Yes! I think the constant name could be changed to something better!
